### ISSUE TITLE
Windows Does not have SIGKILL

### ISSUE THREAD

**Issue by amirhessam88** [pathbird/poetry-kernel#3]
I believe the following line needs more attention to be compatible with Windows considering windows does not have SIGKILL: 
https://github.com/pathbird/poetry-kernel/blob/main/poetry_kernel/__main__.py#L39

**Comment by travigd** [comment]
Does this actually cause any issues? Is `SIGKILL` not defined on Windows?

**Comment by amirhessam88** [comment]
Yeah; I am personally a Mac user I could easily use poetry kernel for any projects and use it in Jupyter Lab. However, I tried to do the same thing for a friend of mine who is a Windows user, and I could not. I ended up adding the kernel manually as shown here https://queirozf.com/entries/jupyter-kernels-how-to-add-change-remove; The error I was getting was related to SIGKILL that could not be found on Windows.

**Comment by travigd** [comment]
Happy to accept a PR that has separate logic for defining a different `forward_signals` set for Windows versus Mac/Linux.

Based on the code, it's not actually the `SIGKILL` causing the issue (we actually remove `SIGKILL` from the set of signals under consideration for forwarding). Instead we should just define the signal set to be the ones you suggested above (on Windows at least).

**Comment by travigd** [comment]
Thanks! Closed in #4 and released as v0.1.2.
